function Rec=FraRec3D(C,R,L)

% function Rec=FraRec(C,R,L)
% This function implement framelet reconstruction.
% C ==== the data to be reconstructed, which are in cells in C{i,j} with
% C{1,1} being a cell.
% R ==== is the reconstruction filter in 1D. In 2D, it is generated by tensor
% product. The filter D must be symmetric or anti-symmetric, which
% are indicated by 's' and 'a' respectively in the last cell of R.
% L ==== is the level of the decomposition.
% Rec ==== is the reconstructed data.

nR=length(R);
SorAS=R{nR};

ImSize=size(C{1,1});
Rec=(zeros(ImSize));

for i=1:nR-1
    temp1=(zeros(ImSize));
    for j=1:nR-1
        temp2=(zeros(ImSize));
        for k=1:nR-1
            M3=R{k};
            temp2=temp2+ipermute(ConvSymAsym3D(permute(C{i,j,k},[3 2 1]),M3,SorAS(k),L),[3 2 1]);
        end
        M2=R{j};
        temp1=temp1+ConvSymAsym3D(temp2,M2,SorAS(j),L);
    end
    M1=R{i};
    Rec=Rec+ipermute(ConvSymAsym3D(permute(temp1,[2 1 3]),M1,SorAS(i),L),[2 1 3]);
end