function Dec=FraDecMultiLevel3D(A,D,L)

% function Dec=FraDec3DMultiLevel(A,D,L)
% This function implement framelet decomposition up to level L.
% A ==== the data to be decomposed, which should be a 3D array.
% D ==== is the decomposition filter in 1D. In 3D, it is generated by tensor
% product. The filter D must be symmetric or anti-symmetric, which
% are indicated by 's' and 'a' respectively in the last cell of D.
% L ==== is the level of the decomposition.
% Dec ==== is the framlet coefficient which are in a cell.

% Written by Jian-Feng Cai. Modified to 3D by Bin Dong

Dec=cell(1,L);

for k=1:L
    Dec{k}=FraDec3D(A,D,k);
    A=Dec{k}{1,1};
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%